//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGenerator.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    public partial class Curriculum
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string profesion { get; set; }
        public Nullable<int> nacionalidad { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string github { get; set; }
        public string objetivos { get; set; }
        public string resumen_ejecutivo { get; set; }
    
        public virtual Pais Pais { get; set; }

        public SelectList Paises { get; set; }

        private IEnumerable<SelectListItem> GetAllPaises()
        {
            CurriculumEntities db = new CurriculumEntities();
            IEnumerable<SelectListItem> list = db.Pais.Select(s => new SelectListItem
            {
                Selected = false,
                Text = s.descripcion,
                Value = s.id.ToString()
            });

            return list;
        }

        public Pais GetPaisById(int? pais_id)
        {
            if (id == null) return null;
            CurriculumEntities db = new CurriculumEntities();
            Pais list = db.Pais.First(i => i.id == pais_id);
            return Pais;
        }
    }
}
